"""empty message

Revision ID: 69820d5ffd1f
Revises: 7d83926702ee
Create Date: 2017-03-12 19:27:05.167083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69820d5ffd1f'
down_revision = '7d83926702ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dwg_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dwg', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dwg_record')
    # ### end Alembic commands ###
