"""empty message

Revision ID: 81ca14133623
Revises: 9a6601b44767
Create Date: 2017-03-04 17:45:29.889861

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81ca14133623'
down_revision = '9a6601b44767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('permission', sa.Integer(), nullable=True))
    op.alter_column('role', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.create_unique_constraint(None, 'role', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='unique')
    op.alter_column('role', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.drop_column('role', 'permission')
    # ### end Alembic commands ###
