"""empty message

Revision ID: 9a6601b44767
Revises: e4c48ef2e199
Create Date: 2017-02-26 01:57:43.523616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a6601b44767'
down_revision = 'e4c48ef2e199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'confirmed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('user', 'password_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('user', 'role_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('user', 'password_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('user', 'confirmed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###
